title = "Shi's blog"
repo = "https://github.com/shi-yan/codestage"
# need to have the slash
prefix = ""
target = "dist"
url = "http://localhost:8000"
meta_image = "meta.png"
description = """
CodeStage is a static site generator to build JS playground demos."""
google_analytics_id = "G-0N1753LT3Y"

content =[
    "diffusion_models_the_forward_pass",
]
