title = "Shi's blog"
repo = "https://github.com/shi-yan/codestage"
# need to have the slash
prefix = ""
target = "dist"
url = "http://localhost:8000"
description = """
CodeStage is a static site generator to build JS playground demos."""
google_analytics_id = "G-0N1753LT3Y"
discussion_url = "https://github.com/shi-yan/shi-yan.github.io/discussions"
logo = "326807.jpeg"

content =[
    "diffusion_models_the_forward_pass",
]
